---
title: "svm_project"
author: "Danila Rozhevskii"
date: "2022-11-17"
---

```{r}
library(tidyverse)

```

```{r}
#loading the dataset
library('readxl')
data <- read_xlsx("C:\\Users\\Aruneema\\Desktop\\MSBA\\IST 687\\Project\\HMO_data.xlsx")
```

```{r}
#converting dataset into dataframe
data <- as.data.frame(data)
```

```{r}
#finding the structure of dataset
str(data)
```

```{r}
table(data$gender)
```

```{r}
#using unclass method to encode smokers into '1' and '2' 
unclass(as.factor(data$smoker))

```

```{r}
#another method to encode smokers into '0' and '1'
ifelse(data$smoker == "yes", 1, 0)
```

```{r}
#converting all the the variables into numeric data type and encoding the categorical variables using 'unclass' and 'ifelse' method
data_new <- data.frame(id=as.numeric(data$X),
                     age=as.numeric(data$age),
                     bmi=as.numeric(data$bmi),
                     children=as.numeric(data$children),
                     smoker=as.numeric(ifelse(data$smoker == 'yes',1,0)),
                     location=as.numeric(unclass(as.factor(data$location))),
                     location_type=as.numeric(ifelse(data$location_type == 'Country',1,0)),
                     education_level=as.numeric(unclass(as.factor(data$education_level))),
                     yearly_physical=as.numeric(ifelse(data$yearly_physical == 'Yes',1,0)),
                     exercise=as.numeric(ifelse(data$exercise == 'Active',1,0)),
                     married=as.numeric(ifelse(data$married == 'Married',1,0)),
                     hypertension = as.numeric(data$hypertension),
                     gender=as.numeric(ifelse(data$gender == 'male',1,0)),
                     cost=as.numeric(data$cost))
                     
                     
```

```{r}
head(data_new)
```

```{r}
#making a new dataframe, 'data_new' which has scaled variables so that the data is normalised

data_new[c('age','bmi','children','location','education_level','cost','exercise','smoker', 'hypertension')] <- 
  scale(data_new[c('age','bmi','children','location','education_level','cost','exercise','smoker', 'hypertension')])
```


```{r}
head(data_new)
```

```{r}
# making another dataframe 'data_new2' having the relevant variables. These variables were choosen from output of lmOut1
data_new2 <- data_new[c('age','bmi', 'smoker','exercise', 'hypertension', 'children')]
```

```{r}

library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
```


```{r}
#k-means clustering

kmodel <- kmeans(data_new2, centers = 2, nstart = 25)
str(kmodel)
```

```{r}
#getting output of the model. The output shows the sclaed mean of two clusters and the cluster vector output
kmodel
```

```{r}
#visualizing the two clusters
fviz_cluster(kmodel, data = data_new)
```

```{r}

data_new %>%
  mutate(Cluster = kmodel$cluster) %>%
  group_by(Cluster) %>%
  summarise_all("mean")
```


```{r}
#appending the cluster colmun to data_new dataframe
data_new['cluster'] <- kmodel$cluster
```

```{r}
head(data_new)
```
```{r}
fviz_cluster(kmodel, data = data_new)
```

```{r}
#appending the cluster colmun to original 'data' dataframe
data['cluster'] <- data_new$cluster
```

```{r}
data %>%
  group_by(cluster) %>%
  summarise_all("mean")
```

```{r}
#labelling people as 'Yes' expensive if they belong to cluster 1 'No' if they belong to cluster 2
data['expensive'] <- ifelse(data$cluster == 1, "yes", "no")
```

```{r}
head(data)
```



```{r}
#age+cost
ggplot(data) + 
  geom_point(mapping = aes(x = age, y = cost, color = expensive))

#bmi+cost
ggplot(data) + 
  geom_point(mapping = aes(x = bmi, y = cost, color = expensive))

```

```{r}
ggplot(data) + 
  geom_bar(mapping = aes(x = exercise, fill = expensive), position = "dodge")

ggplot(data) + 
  geom_bar(mapping = aes(x = gender, fill = expensive), position = "dodge")

ggplot(data) + 
  geom_bar(mapping = aes(x = children, fill = expensive), position = "dodge")

ggplot(data) + 
  geom_bar(mapping = aes(x = education_level, fill = expensive), position = "dodge")


ggplot(data) + 
  geom_bar(mapping = aes(x = location, fill = expensive), position = "dodge")

ggplot(data) + 
  geom_bar(mapping = aes(x = location_type, fill = expensive), position = "dodge")

ggplot(data) + 
  geom_bar(mapping = aes(x = married, fill = expensive), position = "dodge")
```







